default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: pokemon
  username: root
  host: 10.0.0.5
  port: 3306
  password: docker
  encoding: utf8  

